yaml_path: /data/home/zhoupc/github/ease_project/scripts/ease_config.yaml
output_folder: /data/home/zhoupc/github/ease_project/scripts/results
matfile_video: /data/paninski_lab/Tolias_lab/functional_data_analysis/functional_data.mat
video_shifts:
  ii:
  - [0.0, 0.0, -1.0]
  - [-6.0, -6.0, -6.0]
  - [-5.0, -5.0, -6.0]
  - [-6.0, -6.0, -6.0]
  - [-5.0, -5.0, -5.0]
  - [-3.0, -4.0, -4.0]
  - [-3.0, -3.0, -3.0]
  - [-3.0, -3.0, -4.0]
  jj:
  - [2.0, 2.0, 2.0]
  - [0.0, 0.0, -1.0]
  - [0.0, -1.0, 0.0]
  - [-1.0, -1.0, -1.0]
  - [-2.0, -2.0, -2.0]
  - [-3.0, -3.0, -3.0]
  - [-1.0, -1.0, -1.0]
  - [-2.0, -2.0, -2.0]
video_zvals:
- [168.0, 159.0, 153.0]
- [147.0, 139.0, 133.0]
- [122.0, 112.0, 107.0]
- [99.0, 91.0, 85.0]
- [73.0, 67.0, 58.0]
- [58.0, 50.0, 45.0]
- [39.0, 29.0, 23.0]
- [17.0, 6.0, 2.0]
video_zvals_updated:
- [169.0, 160.0, 153.0]
- [147.0, 137.0, 131.0]
- [121.0, 113.0, 107.0]
- [100.0, 92.0, 85.0]
- [78.0, 66.0, 60.0]
- [59.0, 50.0, 45.0]
- [39.0, 29.0, 22.0]
- [17.0, 6.0, 2.0]
video_Fs: 15.0
video_T: 8781.0
denoised_folder: /data/paninski_lab/Tolias_lab/cropped_denoised/
raw_folder: /data/paninski_lab/Tolias_lab/cropped/
use_denoise: false
matfile_stack: /data/lab/Dropbox/Tolias_PC/em_2p_pipeline/data/functional_data/stack_2p.mat
stack_shifts:
  ii:
  - [1.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
  - [1.0, 0.0, 0.0]
  - [1.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  jj:
  - [1.0, 1.0, 1.0]
  - [1.0, 1.0, 0.0]
  - [1.0, 0.0, 1.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [-1.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -1.0]
matfile_transformation: /data/lab/Dropbox/Tolias_PC/em_2p_pipeline/coor_convert.mat
d1: 59.0
d2: 130.0
d3: 3.0
extra_margin: 5.0
FOV: [112.0, 170.0, 39.0, 168.0]
FOV_stack: [223.0, 340.0, 77.0, 336.0]
align_max_zshift: 8.0
num_scans: 8.0
num_slices: 3.0
num_blocks: 3.0
dims_stack: [512.0, 512.0, 310.0]
dims_video: [256.0, 256.0]
range_2p: [400.0, 400.0, 310.0]
scan_id: 1.0
slice_id: 1.0
block_id: 1.0
options_init: {init_method: tf, order_statistics: thresh, min_similarity: 0.6, clear_results: true,
  save_fig: true, K_candidate: 1000.0}
init_method: regression
show_init: true
pause_init: false
maxIter_init: 1.0
show_em_only: false
match_mask: true
matfile_em: /data/paninski_lab/Tolias_lab/EM/em.mat
em_shifts:
  ii:
  - [-2.0, -2.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-2.0, -2.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-2.0, -2.0, -2.0]
  - [-2.0, -3.0, -3.0]
  - [-2.0, -3.0, -3.0]
  - [-3.0, -3.0, -3.0]
  jj:
  - [1.0, 1.0, 1.0]
  - [1.0, 1.0, 0.0]
  - [1.0, 0.0, 1.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [-1.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -1.0]
em_load_flag: true
em_zblur: 6.0
PACK_SIZE: 64.0
score_method: corr
nam_show: cn
