yaml_path: /data/home/zhoupc/github/ease_project/scripts/pinky100_config.yaml
data_folder: /data/home/zhoupc/github/ease_project/data/pinky100
output_folder: /data/home/zhoupc/github/ease_project/results/pinky100
denoised_folder: cropped_denoised_video
raw_folder: cropped_raw_video
matfile_video: functional_data.mat
matfile_stack: stack_2p.mat
registration_csv: registration.csv
matfile_transformation: coor_convert.mat
matfile_em: em.mat
video_shifts:
  ii:
  - [0.0, 0.0, -1.0]
  - [-6.0, -6.0, -6.0]
  - [-5.0, -5.0, -6.0]
  - [-6.0, -6.0, -6.0]
  - [-5.0, -5.0, -5.0]
  - [-3.0, -4.0, -4.0]
  - [-3.0, -3.0, -3.0]
  - [-3.0, -3.0, -4.0]
  jj:
  - [2.0, 2.0, 2.0]
  - [0.0, 0.0, -1.0]
  - [0.0, -1.0, 0.0]
  - [-1.0, -1.0, -1.0]
  - [-2.0, -2.0, -2.0]
  - [-3.0, -3.0, -3.0]
  - [-1.0, -1.0, -1.0]
  - [-2.0, -2.0, -2.0]
video_zvals:
- [168.0, 159.0, 153.0]
- [147.0, 139.0, 133.0]
- [122.0, 112.0, 107.0]
- [99.0, 91.0, 85.0]
- [73.0, 67.0, 58.0]
- [58.0, 50.0, 45.0]
- [39.0, 29.0, 23.0]
- [17.0, 6.0, 2.0]
video_zvals_updated:
- [169.0, 160.0, 153.0]
- [147.0, 137.0, 131.0]
- [121.0, 113.0, 107.0]
- [100.0, 92.0, 85.0]
- [78.0, 66.0, 60.0]
- [59.0, 50.0, 45.0]
- [39.0, 29.0, 22.0]
- [17.0, 6.0, 2.0]
video_Fs: 15.0
video_T: 9100.0
use_denoise: false
stack_shifts:
  ii:
  - [1.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [1.0, 1.0, 1.0]
  - [1.0, 0.0, 0.0]
  - [1.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  jj:
  - [1.0, 1.0, 1.0]
  - [1.0, 1.0, 0.0]
  - [1.0, 0.0, 1.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [-1.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, -1.0]
d1: 59.0
d2: 130.0
d3: 3.0
extra_margin: 5.0
FOV: [112.0, 170.0, 39.0, 168.0]
FOV_stack: [223.0, 340.0, 77.0, 336.0]
align_max_zshift: 8.0
num_scans: 8.0
num_slices: 3.0
num_blocks: 3.0
dims_stack: [512.0, 512.0, 310.0]
dims_video: [256.0, 256.0]
range_2p: [400.0, 400.0, 310.0]
scan_id: 1.0
slice_id: 1.0
block_id: 1.0
options_init: {init_method: semi-NMF, order_statistics: ss3mad, min_similarity: 0.6,
  clear_results: false, save_fig: false, K_candidate: 3000.0, show_fig: true, K_new: 50.0}
init_method: regression
show_init: true
pause_init: false
maxIter_init: 1.0
show_em_only: false
match_mask: true
em_shifts:
  ii:
  - [-2.0, -2.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-2.0, -2.0, -3.0]
  - [-3.0, -3.0, -3.0]
  - [-2.0, -2.0, -2.0]
  - [-2.0, -3.0, -3.0]
  - [-2.0, -3.0, -3.0]
  - [-3.0, -3.0, -3.0]
  jj:
  - [3.0, 3.0, 3.0]
  - [3.0, 3.0, 2.0]
  - [3.0, 2.0, 3.0]
  - [2.0, 2.0, 2.0]
  - [2.0, 3.0, 2.0]
  - [1.0, 2.0, 2.0]
  - [2.0, 2.0, 2.0]
  - [2.0, 2.0, 1.0]
em_load_flag: true
em_zblur: 6.0
PACK_SIZE: 64.0
score_method: corr
nam_show: cn
